name: 刷课

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    env:
      CHAOXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
      CHAOXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
      CHAOXING_COURSE_ID: ${{ secrets.CHAOXING_COURSE_ID }}
      CHAOXING_TIKU_TOKEN: ${{ secrets.CHAOXING_TIKU_TOKEN }}
      CHAOXING_TIKU_URL: https://oneapi.naujtrats.xyz/v1
      CHAOXING_TIKU_MODEL: deepseek-v4-flash
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v4

      - name: 设置python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖包
        run: pip install -r requirements.txt

      - name: 生成配置文件
        run: python generate_config.py

      - name: Run main.py
        run: python main.py -c config.ini