name: 刷课

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      CHAOXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
      CHAOXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
      CHAOXING_COURSE_ID: ${{ secrets.CHAOXING_COURSE_ID }}
      CHAOXING_TIKU_TOKEN: ${{ secrets.CHAOXING_TIKU_TOKEN }}
      CHAOXING_TIKU_URL: https://oneapi.naujtrats.xyz/v1
      CHAOXING_TIKU_MODEL: deepseek-v4-flash
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v4

      - name: 设置python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖包
        run: pip install -r python/requirements.txt

      - name: Run main.py
        run: cd python/chaoxing && python main.py -u "$CHAOXING_USERNAME" -p "$CHAOXING_PASSWORD" -l "$CHAOXING_COURSE_ID" -s 2.0